# Generated by Django 3.2.12 on 2023-03-06 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ilmp_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Correo',
        ),
    ]
